version: '3'
services: 
  redis:
    image: redis
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - 8080:8080
    volumes:
      - .:/code
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["python", "test.py"] 
    volumes: 
      - .:/code
